### ISSUE TITLE
It just crashed.

### ISSUE THREAD

**Issue by KrischnaGabriel** [dsharlet/LiveSPICE#113]
Well.. i tried to run LiveSpice for the first time and it threw out this error:
What happened?

System.Windows.Markup.XamlParseException: Set property 'LiveSPICE.MenuItemIcon.CommandImage' threw an exception. ---> System.TypeInitializationException: The type initializer for 'LiveSPICE.Images' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.WebRequest.get_PrefixList()
   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   at System.Net.WebRequest.Create(Uri requestUri)
   at MS.Internal.WpfWebRequestHelper.CreateRequest(Uri uri)
   at System.Windows.Media.ColorContext.Initialize(Uri profileUri, Boolean isStandardProfileUriNotFromUser)
   at System.Windows.Media.ColorContext..ctor(PixelFormat pixelFormat)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource)
   at LiveSPICE.Images..cctor()
   --- End of inner exception stack trace ---
   at LiveSPICE.Images.ForCommand(ICommand Command)
   at LiveSPICE.MenuItemIcon.set_CommandImage(ICommand value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

SystemInformations:
OS: Win 8.1
LiveSpice: latest release  (v0.13  Preview 13)

I wanted to try it out, see if it's a good & useful software but can't seem to get it to run.  :I

**Comment by caiodeaguiar** [comment]
I've got the same issue. I was using it until yesterday and all of a sudden it started crashing and giving me these errors. I tried uninstalling and reinstalling, the same with Microsoft .NET 6.0 runtime. Anyone to shine some light on the matter?
